import "./globals.css";
import clsx from "clsx";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={clsx(
          inter.className,
          "flex-center h-screen bg-branding-white"
        )}
      >
        <section className="border-2 border-branding-black w-[375px] h-[844px]">
          {children}
        </section>
      </body>
    </html>
  );
}
